development:
  bucket_name: gletscherspalter_on_rails_development
  access_key_id: 1YPXKCJ7TJVD3P18H3G2
  secret_access_key: Gfuih4XpDO8oZh0QMr9ofeJBK0Yni7RiB+agovUN

test:
  bucket_name: gletscherspalter_on_rails_test
  access_key_id: 
  secret_access_key: 

production:
  bucket_name: gletscherspalter_on_rails_production
  access_key_id: 1YPXKCJ7TJVD3P18H3G2
  secret_access_key: Gfuih4XpDO8oZh0QMr9ofeJBK0Yni7RiB+agovUN