# Mail settings
mail:
  server: 'mail.gletscherspalter.ch'
  domain: 'www.gletscherspalter.ch'
  user_name: 'no-reply+gletscherspalter.ch'
  password: '-p?!?fYvdivU'

# Google Maps
gmaps:
  api-key: "ABQIAAAA5Cg2aLm1iTTYL6oUisE3ZBSuXVNLgnrcQJUWSG2AreT3guZgphSOO4UVDmj7UXBqb8uhZ0n4unLssg"
  api-key-old: "ABQIAAAA5HvxKEk6euzB7DUyH0_WQRTpKOENAK7M60P_iZyjsCmeWfdXDBRvBLY2QxpZG45FwPCzYLQvO4CdXw"

# Flickr Account details
flickr:
  api-key: "02c75fd7a65f0e72affa799b7105afc9"
  shared-secret: "3125e4dc1dd61ad4"
  user-id: "44777339@N04"
  auth-token: "72157622835493126-87c74181a6135d00"
