development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
  encoding: utf8

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
  encoding: utf8

production:
  adapter: mysql
  database: gletscherspalter_production
  username: root
  password: 
  socket: /tmp/mysql.sock
  encoding: utf8